
spring:
  application:
    name: UserProvider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url:  jdbc:mysql://192.168.188.138:3308/jpa001?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
