spring:
  application:
    name: UserProvider01
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url:  jdbc:mysql://db1:3309/jpa001?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
